import sys
import os


def init_words(dev=False, cmd=False):
    if cmd:
        add_parent_to_path()

    from data import db_session
    from data.theme import Theme
    from data.word import Word

    db_session.global_init(dev)
    db_sess = db_session.create_session()

    def add_theme(id_str, name, words):
        theme = Theme(id_str=id_str, name=name)
        db_sess.add(theme)
        db_sess.commit()
        for (trans, name) in words:
            if isinstance(trans, str):
                trans = [trans]
            db_sess.add(Word(name=name, trans=trans, themeId=theme.id))
        db_sess.commit()

    def init():
        add_theme("w1_t1_1", "Theme 1.1", [
            ("enterprise", "предприятие"),
            ("first-year student", "студент-первокурсник"),
            ("Institute of Artificial Intelligence", "Институт Искусственного Интеллекта"),
            ("jogging", "бег трусцой"),
            ("precious", "драгоценный, любимый"),
            ("programmer", "программист"),
            ("robotics engineer", "инженер-робототехник"),
            ("support", "поддержка, помощь, опора"),
            ("system analyst", "системный аналитик"),
            (["to follow the tradition", "follow the tradition", "to follow tradition", "follow tradition"], "следовать традициям"),
            (["to go hiking", "go hiking"], "ходить в походы"),
            (["to introduce", "introduce"], "знакомить, представлять"),
            (["to share smth with smb", "share smth with smb"], "делиться чем-то с кем-то"),
            (["to solve problems", "solve problems"], "разрешать проблемы"),
            (["to take pictures", "take pictures"], "фотографировать"),
            (["to work for a company", "work for a company", "to work for company", "work for company"], "работать в компании"),
            ("understanding", "понимание"),
        ])
        add_theme("w1_t1_2", "Theme 1.2", [
            ("benefits", "преимущества"),
            ("entertainment", "развлечение"),
            ("fascinating", "увлекательный, чрезвычайно интересный"),
            ("hobby", "хобби, любимое занятие"),
            ("inner world", "внутренний мир"),
            ("occupation", "профессия, род занятий"),
            ("pastime", "приятное времяпрепровождение"),
            ("rare", "редкий"),
            ("rewarding", "приносящий внутреннее удовлетворение, дающий результат"),
            ("sense of purpose", "целеустремленность"),
            ("skills", "навыки, умения"),
            (["to be in high spirits", "be in high spirits"], "быть в хорошем/приподнятом настроении"),
            (["to bring happiness", "bring happiness"], "приносить счастье"),
            (["to collect", "collect"], "собирать"),
            (["to enrich", "enrich"], "обогащать"),
            (["to have a passion for", "have a passion for", "to have passion for", "have passion for"], "увлекаться чем либо"),
            (["to improve", "improve"], "улучшать"),
            (["to look forward to smth", "look forward to smth"], "ждать с нетерпением"),
            (["to master", "master"], "овладевать, совершенствовать"),
            (["to prefer", "prefer"], "предпочитать"),
            (["to stay focused on", "stay focused on"], "сконцентрироваться на чем-то"),
        ])
        add_theme("w1_t1_3", "Theme 1.3", [
            ("acquired skills", "приобретенные навыки"),
            ("cheerful and positive attitude", "радостный и позитивный настрой"),
            ("contribute significantly", "сделать значительный вклад"),
            ("equipment", "оборудование"),
            ("great sense of humor", "отличное чувство юмора"),
            ("highest score", "высший балл"),
            ("highly-educated", "высокообразованный"),
            ("humanity", "человечность"),
            ("merchant", "купец/торговец"),
            ("native wit", "врожденное остроумие"),
            ("secondary education", "среднее образование"),
            ("staff", "сотрудники"),
            ("stringent requirements", "строгие требования"),
            (["to be engaged in", "be engaged in"], "быть вовлеченным в"),
            (["to pass away", "pass away"], "скончаться"),
            (["to surround", "surround"], "окружать"),
            ("transmitting and receiving information", "передача и получение информации"),
            ("vivid example", "живой пример"),
            ("wealthy", "богатый"),
            ("wisdom", "мудрость"),
        ])
        add_theme("w1_t2_1", "Theme 2.1", [
            ("academic achievements", "академическая успеваемость"),
            ("academic research", "научное исследование"),
            ("apprenticeship", "ученичество, стажировка"),
            (["bachelor's degree", "bachelors degree"], "степень бакалавра"),
            ("completion", "завершение, окончание"),
            ("conversion course", "курс переподготовки"),
            ("employment", "трудоустройство"),
            ("experience", "опыт"),
            (["FE (Further education) college", "FE college", "further education college"], "колледж профессионального образования"),
            (["to apply for (to)", "apply for (to)", "to apply for", "apply for", "to apply to", "apply to"], "подать заявление, записаться"),
            (["to award", "award"], "присвоить. присудить"),
            (["to be referred to as", "be referred to as"], "называться"),
            (["to complete", "complete"], "получить, завершить"),
            (["to enrol in", "enrol in", "to enroll in", "enroll in"], "поступить, записаться"),
            (["to enter", "enter"], "поступить"),
            (["to pursue", "pursue"], "учиться с целью получения новой степени или знаний"),
            (["Master's course", "Masters course"], "магистратура"),
            ("postgraduate", "аспирант, лицо, имеющее базовое высшее образование"),
            ("sandwich course", "курс, совмещающий теорию и практику"),
            ("term", "семестр"),
            ("vocational", "профессиональный"),
        ])
        add_theme("w1_t2_2", "Theme 2.2", [
            ("compulsory", "обязательный, общеобразовательный"),
            ("credit hours", "единица учебной нагрузки, определённое количество которых необходимо набрать для получения зачёта"),
            ("dedication", "стремление, сосредоточенность, усердие"),
            ("elective", "факультативный, элективный, по выбору"),
            ("eligibility", "соответствие установленным требованиям, критериям"),
            ("extensively", "много, активно, в больших количествах"),
            ("grades", "баллы, оценки"),
            ("major", "ведущее направление подготовки, специальность, основной предмет"),
            (["to achieve", "achieve"], "достигать, добиваться, выполнять"),
            (["to aim", "aim"], "стремиться, ставить целью"),
            (["to determine", "determine"], "определять, обуславливать"),
            (["to evolve", "evolve"], "развиваться, изменяться"),
            (["to fulfil", "fulfil"], "выполнять, соответствовать"),
            (["to major", "major"], "специализироваться в изучении какого-либо предмета"),
            (["to specialise in", "specialise in"], "специализироваться на чем-то"),
            (["to tailor", "tailor"], "приспосабливать, проектировать, специально разрабатывать"),
            ("requirements", "требования"),
        ])
        add_theme("w1_t2_3", "Theme 2.3", [
            ("admission", "поступление, прием"),
            ("competitive", "на конкурсной основе"),
            ("comprehensive", "общеобразовательный, всесторонний"),
            ("contribution", "вклад, содействие"),
            ("core subjects", "основные, базовые предметы"),
            ("curriculum", "учебная программа"),
            ("high academic performance", "превосходная академическая успеваемость"),
            ("highly skilled", "высококвалифицированный"),
            ("humanities", "гуманитарные предметы"),
            ("opportunity", "возможность"),
            (["to advance", "advance"], "продвигать, развивать"),
            (["to last", "last"], "продолжаться, длиться"),
            (["to specialise in engineering in depth", "specialise in engineering in depth"], "углубляться в изучение инженерных наук /получить специализацию"),
            ("training", "обучение, подготовка"),
            ("Uniform State Examination", "Единый Государственный Экзамен"),
            ("well-rounded education", "всестороннее образование"),
        ])
        add_theme("w1_t3_1_1", "Theme 3.1.1", [
            ("aircraft", "самолет/авиастроение воздушное судно"),
            ("cattle", "крупный рогатый скот"),
            ("cereals", "злаковые культуры"),
            ("chemicals", "химикаты, химическая продукция"),
            ("coal", "уголь"),
            ("coastline", "побережье"),
            ("conquest", "завоевание"),
            ("descendant", "потомок"),
            ("hill", "холм"),
            ("horticulture", "садоводство"),
            ("invasion", "вторжение"),
            ("island", "остров"),
            ("maritime", "морской"),
            ("mild", "мягкий"),
            ("motor vehicle", "автомобиль, моторное транспортное средство"),
            ("mountain", "гора"),
            ("oilseed", "семя масличного растения"),
            ("peninsula", "полуостров"),
            ("petroleum", "нефтепродукты"),
            ("poultry", "домашняя птица, птицеводство"),
            ("railroad", "железная дорога"),
            ("rolling plain", "холмисто-равнинная местность"),
            ("rugged", "пересеченный (о местности)"),
            ("shipbuilding", "кораблестроение"),
            ("temperate", "умеренный"),
            ("topography", "рельеф, ландшафт, топография"),
            (["to aid in", "aid in"], "помогать, способствовать"),
            (["to appease", "appease"], "умиротворять"),
            (["to be located", "be located"], "быть расположенным"),
            (["to be made up of", "be made up of"], "состоять из"),
            (["to succeed", "succeed"], "следовать за, быть преемником"),
            ("undeveloped", "неразвитый"),
            ("valley", "долина"),
        ])
        add_theme("w1_t3_1_2", "Theme 3.1.2", [
            ("assembly", "собрание, ассамблея"),
            ("authority", "полномочие, орган власти"),
            ("ballot", "голосование"),
            ("ballots", "бюллетени для голосования"),
            ("bicameral", "состоящий из двух палат"),
            ("bill", "законопроект"),
            ("constituency", "избирательный округ"),
            ("elections", "выборы"),
            ("executive", "исполнительный"),
            ("House of Commons", "Палата общин"),
            ("House of Lords", "Палата лордов"),
            ("issue", "предмет, вопрос"),
            ("judicial", "судебный"),
            ("legal document", "юридический документ"),
            ("legislative", "законодательный"),
            ("Member of Parliament", "член парламента, депутат"),
            (["on the contrary", "on contrary"], "напротив, наоборот"),
            ("political parties", "политические партии"),
            ("select committee", "специальный комитет"),
            ("senior minister", "главный министр"),
            (["to be beholden to", "be beholden to"], "подчиняться, быть подотчетным"),
            (["to enforce", "enforce"], "обеспечивать соблюдение"),
            (["to ensure", "ensure"], "обеспечивать, гарантировать"),
            (["to govern", "govern"], "управлять, руководить"),
            (["to head", "head"], "возглавлять"),
            (["to implement", "implement"], "выполнять, осуществлять, реализовывать"),
            (["to make laws", "make laws"], "создавать законы, заниматься законотворческой деятельностью"),
            (["to prosecute", "prosecute"], "преследовать в судебном порядке, привлекать к суду"),
            (["to respond", "respond"], "отвечать, реагировать"),
            (["to run the government", "run the government", "to run government", "run government"], "управлять государством"),
            (["to scrutinize", "scrutinize"], "тщательно изучать"),
            (["to take place", "take place"], "проходить, состояться"),
            ("ultimately", "в конечном итоге"),
            ("uncodified", "некодифицированный"),
        ])
        add_theme("w1_t3_2_1", "Theme 3.2.1", [
            ("agricultural output", "сельскохозяйственное производство"),
            ("by virtue of", "по причине, в силу чего то"),
            ("consumer goods", "потребительские товары"),
            ("diverse population", "разнообразное население"),
            ("economic self-sufficiency", "экономическая самодостаточность"),
            ("environment", "среда"),
            ("ethnic", "этнический"),
            ("gasoline", "топливо"),
            ("grain", "зерно, зерновые культуры"),
            ("immense", "огромный"),
            ("indigenous", "коренной"),
            ("investment capital", "инвестиционный капитал"),
            ("landscape", "пейзаж"),
            ("lumber", "пиломатериалы, древесина"),
            ("mining", "горнодобывающая промышленность"),
            ("moist", "влажный"),
            ("mountain ranges", "горные хребты"),
            (["nation's wealth", "nations wealth"], "национальное богатство, богатство страны"),
            ("Native Americans", "коренные американцы"),
            ("racial", "расовый"),
            ("sheer", "чистый"),
            ("source", "источник"),
            ("subregion", "субрегион"),
            (["to border on", "border on"], "граничить"),
            (["to enrich", "enrich"], "обогатить"),
            (["to feature", "feature"], "включать, содержать, иметь"),
            (["to impinge on", "impinge on"], "оказывать влияние на что-то"),
            (["to owe", "owe"], "быть обусловленным, обязанным"),
            ("wheat", "пшеница"),
        ])
        add_theme("w1_t3_2_2", "Theme 3.2.2", [
            ("article", "статья"),
            ("autocratic rule", "автократическое правление"),
            ("census", "перепись населения"),
            ("circuit court", "окружной суд (США)"),
            ("commander-in-chief", "верховный главнокомандующий"),
            ("district court", "федеральный окружной суд (США)"),
            ("division of powers", "разделение властей"),
            ("emergence", "появление"),
            ("governmental structures", "государственные структуры"),
            ("healthcare", "здравоохранение"),
            ("legislative body", "законодательный орган"),
            ("system of checks and balances", "система сдержек и противовесов"),
            ("tie-breaking vote", "решающий голос"),
            (["to abide", "abide"], "подчиняться"),
            (["to appoint", "appoint"], "назначать"),
            (["to assume duties", "assume duties"], "брать на себя обязанности"),
            (["to be charged with", "be charged with"], "быть ответственным за, обвиняться в чем-либо"),
            (["to be entitled", "be entitled"], "иметь полномочия"),
            (["to impeach", "impeach"], "объявить импичмент"),
            (["to overlap", "overlap"], "перекрывать/наслаиваться"),
            (["to override veto", "override veto"], "преодолевать вето"),
            (["to reject a law", "reject a law", "to reject law", "reject law"], "отклонить закон"),
            (["to try and convict", "try and convict"], "привлекать к ответственности и признавать виновным"),
            ("treaty", "договор, межгосударственный договор"),
        ])
        add_theme("w1_t3_3", "Theme 3.3", [
            ("armaments", "вооружение"),
            ("barley", "ячмень"),
            ("biome", "биом / природная зона"),
            ("cardboard", "картон"),
            ("caviar", "икра"),
            ("cod", "треска"),
            ("coniferous", "хвойный"),
            ("draft law", "законопроект"),
            ("duties", "обязанности"),
            ("export income", "поступления от экспорта"),
            ("federal entity", "субъект Федерации"),
            ("freshwater", "пресная вода"),
            ("grassland", "степь / луг"),
            ("herring", "сельдь"),
            ("hydroelectric power", "гидроэлектроэнергия"),
            ("implementation", "внедрение / исполнение"),
            ("iron ore", "железная руда"),
            ("irrigation", "орошение"),
            ("nonferrous metals", "цветные металлы"),
            ("oats", "овес"),
            ("permafrost", "вечная мерзлота"),
            (["policy (domestic, foreign, financial, monetary)", "policy"], "политика (внутренняя, внешняя, финансовая, денежно-кредитная)"),
            ("pollack", "сайда"),
            ("precious metals", "драгоценные металлы"),
            ("pulp", "целлюлоза"),
            ("regional body", "региональный орган"),
            ("roundwood", "лес-кругляк"),
            ("rye", "рожь"),
            ("salmon", "лосось"),
            ("seafood", "морепродукты"),
            ("soil", "почва"),
            ("state decoration", "государственная награда"),
            ("sterlet", "стерлядь"),
            ("term", "срок"),
            ("tier", "уровень"),
            ("timber", "лесоматериалы"),
            ("time zone", "часовой пояс"),
            (["to be renowned", "be renowned"], "быть широко известным"),
            (["to be vested", "be vested"], " быть наделенным правами"),
            (["to resolve issues", "resolve issues"], "разрешать вопросы"),
            (["to span", "span"], "охватывать"),
            (["to stretch through", "stretch through"], "протягиваться через"),
        ])
        add_theme("w1_t4_1", "Theme 4.1", [
            ("excuse", "отговорка, оправдание"),
            ("flavor", "вкус, колорит"),
            ("fluency", "беглость"),
            ("inquisitive", "любознательный"),
            ("relevant", "актуальный, необходимый, нужный"),
            ("route", "путь, способ"),
            ("target", "цель"),
            (["to achieve", "achieve"], "достигать"),
            (["to be wrapped up", "be wrapped up"], "быть вовлечённым"),
            (["to do smth on regular basis", "do smth on regular basis"], "делать что-то на регулярной основе, систематически"),
            (["to envelop", "envelop"], "отражать"),
            (["to express oneself", "express oneself"], "выражать себя, самовыражаться, высказываться"),
            (["to get in-depth with smth", "get in-depth with smth"], "вникать, погружаться во что то"),
            (["to go deeper into", "go deeper into"], "глубже вникать"),
            (["to keep learning", "keep learning"], "продолжать учиться"),
            (["to look back", "look back"], "оглядываться назад, оценивать, анализировать"),
            (["to make sure", "make sure"], "убедиться"),
            (["to set realistic goals", "set realistic goals"], "ставить перед собой реалистичные цели"),
        ])

    init()


def add_parent_to_path():
    current = os.path.dirname(os.path.realpath(__file__))
    parent = os.path.dirname(current)
    sys.path.append(parent)


# (["", ""], ""),
# ("", ""),

if __name__ == "__main__":
    init_words("dev" in sys.argv, True)